export const PHARMACY_PRODUCT_LIST_REQUEST = 'PHARMACY_PRODUCT_LIST_REQUEST';
export const PHARMACY_PRODUCT_LIST_SUCCESS = 'PHARMACY_PRODUCT_LIST_SUCCESS';
export const PHARMACY_PRODUCT_LIST_FAIL = 'PHARMACY_PRODUCT_LIST_FAIL';

export const PHARMACY_PRODUCT_DETAILS_REQUEST = 'PHARMACY_PRODUCT_DETAILS_REQUEST';
export const PHARMACY_PRODUCT_DETAILS_SUCCESS = 'PHARMACY_PRODUCT_DETAILS_SUCCESS';
export const PHARMACY_PRODUCT_DETAILS_FAIL = 'PHARMACY_PRODUCT_DETAILS_FAIL';

export const PHARMACY_PRODUCT_DELETE_REQUEST = 'PHARMACY_PRODUCT_DELETE_REQUEST';
export const PHARMACY_PRODUCT_DELETE_SUCCESS = 'PHARMACY_PRODUCT_DELETE_SUCCESS';
export const PHARMACY_PRODUCT_DELETE_FAIL = 'PHARMACY_PRODUCT_DELETE_FAIL';

export const PHARMACY_PRODUCT_CREATE_REQUEST = 'PHARMACY_PRODUCT_CREATE_REQUEST';
export const PHARMACY_PRODUCT_CREATE_SUCCESS = 'PHARMACY_PRODUCT_CREATE_SUCCESS';
export const PHARMACY_PRODUCT_CREATE_FAIL = 'PHARMACY_PRODUCT_CREATE_FAIL';
export const PHARMACY_PRODUCT_CREATE_RESET = 'PHARMACY_PRODUCT_CREATE_RESET';

export const PHARMACY_PRODUCT_UPDATE_REQUEST = 'PHARMACY_PRODUCT_UPDATE_REQUEST';
export const PHARMACY_PRODUCT_UPDATE_SUCCESS = 'PHARMACY_PRODUCT_UPDATE_SUCCESS';
export const PHARMACY_PRODUCT_UPDATE_FAIL = 'PHARMACY_PRODUCT_UPDATE_FAIL';
export const PHARMACY_PRODUCT_UPDATE_RESET = 'PHARMACY_PRODUCT_UPDATE_RESET';
