export const PHARMACY_LOGIN_REQUEST = 'PHARMACY_LOGIN_REQUEST';
export const PHARMACY_LOGIN_SUCCESS = 'PHARMACY_LOGIN_SUCCESS';
export const PHARMACY_LOGIN_FAIL = 'PHARMACY_LOGIN_FAIL';
export const PHARMACY_LOGOUT = 'PHARMACY_LOGOUT';

export const PHARMACY_REGISTER_REQUEST = 'PHARMACY_REGISTER_REQUEST';
export const PHARMACY_REGISTER_SUCCESS = 'PHARMACY_REGISTER_SUCCESS';
export const PHARMACY_REGISTER_FAIL = 'PHARMACY_REGISTER_FAIL';

export const PHARMACY_LIST_REQUEST = 'PHARMACY_LIST_REQUEST';
export const PHARMACY_LIST_SUCCESS = 'PHARMACY_LIST_SUCCESS'; 
export const PHARMACY_LIST_FAIL    = 'PHARMACY_LIST_FAIL';
export const PHARMACY_LIST_RESET    = 'PHARMACY_LIST_RESET';

export const PHARMACY_DELETE_REQUEST = 'PHARMACY_DELETE_REQUEST';
export const PHARMACY_DELETE_SUCCESS = 'PHARMACY_DELETE_SUCCESS'; 
export const PHARMACY_DELETE_FAIL    = 'PHARMACY_DELETE_FAIL';

export const PHARMACY_UPDATE_REQUEST = 'PHARMACY_UPDATE_REQUEST';
export const PHARMACY_UPDATE_SUCCESS = 'PHARMACY_UPDATE_SUCCESS'; 
export const PHARMACY_UPDATE_FAIL    = 'PHARMACY_UPDATE_FAIL';
export const PHARMACY_UPDATE_RESET    = 'PHARMACY_UPDATE_RESET';

export const PHARMACY_DETAILS_REQUEST = 'PHARMACY_DETAILS_REQUEST';
export const PHARMACY_DETAILS_SUCCESS = 'PHARMACY_DETAILS_SUCCESS';
export const PHARMACY_DETAILS_FAIL = 'PHARMACY_DETAILS_FAIL';